[phases.install]
cmds = ['bun install --filter "./workspaces/bot" --production']

[phases.build]
cmds = []

[start]
# avoid --filter here because bun prefixes log lines and it can't be disabled 🙃
cmd = 'cd ./workspaces/bot && bun start'
